import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { supabaseSchema } from "@orvacon/adapter-supabase";
import type { Command } from "commander";
import { version } from "../../package.json";

const GENERATE_GUIDANCE = `Generated orvacon's core schema + default-deny RLS (printed above).

  1. Review it — especially the RLS policies. This is your payment data's security
     boundary; read what you are about to apply.
  2. Save it:   orvacon generate --write   (-> supabase/migrations/<timestamp>_orvacon.sql)
  3. Apply it:  supabase db push

Keep your service_role key server-only — never expose it to the client or commit
it. service_role bypasses the RLS above by design, so that one key is the only
thing standing outside the boundary.
`;

const APPLY_GUIDANCE = `Review the migration — especially the RLS policies — then apply it:

  supabase db push

Keep your service_role key server-only; it bypasses the RLS above by design.
`;

/**
 * Assemble the migration. v1 emits the core schema only; once connectors and
 * kits can declare their own tables, their contributions would be merged in here.
 */
function migrationSql(): string {
  return `-- orvacon core schema + default-deny RLS.
-- Generated by \`orvacon generate\` (v${version}). Review before applying.

${supabaseSchema()}
`;
}

/** Supabase migration prefix: a 14-digit UTC timestamp, YYYYMMDDHHMMSS. */
function utcStamp(): string {
  return new Date().toISOString().replace(/\D/g, "").slice(0, 14);
}

/** Register `orvacon generate` — print (or write) the schema + default-deny RLS migration. */
export function registerGenerate(program: Command): void {
  program
    .command("generate")
    .description("print the database schema + default-deny RLS migration (--write to save it)")
    .option("-w, --write", "write the migration to supabase/migrations/ instead of printing it")
    .option("-f, --force", "write a new migration even if an orvacon one already exists")
    .option("--adapter <name>", "the database adapter to generate for", "supabase")
    .action((options: { write?: boolean; force?: boolean; adapter: string }) => {
      if (options.adapter !== "supabase") {
        process.stderr.write(`Unknown adapter: ${options.adapter}. v1 supports: supabase\n`);
        process.exit(1);
      }

      const sql = migrationSql();

      // Default: print, so the dev reads the security policy before applying it.
      if (!options.write) {
        process.stdout.write(sql);
        process.stderr.write(`\n${GENERATE_GUIDANCE}`);
        return;
      }

      const dir = join("supabase", "migrations");
      if (existsSync(dir)) {
        const existing = readdirSync(dir).filter((name) => name.endsWith("_orvacon.sql"));
        if (existing.length > 0 && !options.force) {
          process.stderr.write(
            `An orvacon migration already exists:\n  ${join(dir, existing[0])}\n\n` +
              "Refusing to overwrite — your edits (e.g. customized RLS) would be lost.\n" +
              "Delete it and re-run, or pass --force to write a new timestamped migration.\n",
          );
          process.exit(1);
        }
      } else {
        mkdirSync(dir, { recursive: true });
      }

      const file = join(dir, `${utcStamp()}_orvacon.sql`);
      writeFileSync(file, sql);
      process.stderr.write(`Wrote ${file}\n\n${APPLY_GUIDANCE}`);
    });
}
