import type { Brand } from "./brand";

/**
 * Reserved id prefixes across the orvacon ecosystem. Every id type claims its
 * prefix here — one place, no collisions, no near-duplicates (`sub` cannot be
 * re-used by another kit once subscriptions own it). Kits must extend this
 * list before introducing a new prefixed id.
 */
export const ID_PREFIXES = {
  payment: "pay",
  refund: "re",
  event: "evt",
  subscription: "sub",
} as const;

/** A reserved prefix from {@link ID_PREFIXES}. */
export type IdPrefix = (typeof ID_PREFIXES)[keyof typeof ID_PREFIXES];

/**
 * orvacon's own payment identifier — the same value that rides the gateway as
 * `conversationId` / `merchant_oid`.
 *
 * Target format is a prefixed ULID (`pay_01J…`, see {@link ID_PREFIXES}):
 * time-ordered for index locality, prefixed for at-a-glance recognizability.
 * Validation is deliberately minimal (non-empty) until the generator lands
 * with the orchestration body; it will tighten inside {@link paymentId}
 * without touching any call site.
 */
export type PaymentId = Brand<string, "PaymentId">;

/**
 * Validate and brand a payment id.
 *
 * @throws TypeError if the id is empty.
 */
export function paymentId(value: string): PaymentId {
  if (value.length === 0) {
    throw new TypeError("Payment id must be a non-empty string");
  }
  return value as PaymentId;
}

/**
 * Client-generated key that makes a mutating operation safe to retry.
 *
 * One key per *logical intent* (one payment attempt), generated by the caller
 * (e.g. `crypto.randomUUID()`) and reused unchanged on every retry of that same
 * intent — if the core generated it, a retry after a timeout would get a fresh
 * key and bypass deduplication entirely. The core enforces uniqueness atomically
 * in the database (unique constraint) with a bounded TTL; a replayed key returns
 * the original result, never a fresh charge.
 */
export type IdempotencyKey = Brand<string, "IdempotencyKey">;

/**
 * Validate and brand an idempotency key.
 *
 * @throws TypeError if the key is empty or longer than 255 characters.
 */
export function idempotencyKey(value: string): IdempotencyKey {
  if (value.length === 0 || value.length > 255) {
    throw new TypeError(`Idempotency key must be 1-255 characters, got length ${value.length}`);
  }
  return value as IdempotencyKey;
}

/**
 * A mutating request plus its client-generated {@link IdempotencyKey}. Every
 * money-moving call on the orvacon instance is idempotency-keyed; the core
 * consumes the key (dedup, replay) and the connector never sees it.
 */
export type Idempotent<I> = I & { idempotencyKey: IdempotencyKey };
