import type { Brand } from "./brand";

/**
 * Reserved id prefixes across the orvacon ecosystem. Every id type claims its
 * prefix here — one place, no collisions, no near-duplicates (`sub` cannot be
 * re-used by another kit once subscriptions own it). Kits must extend this
 * list before introducing a new prefixed id.
 */
export const ID_PREFIXES = {
  payment: "pay",
  refund: "re",
  event: "evt",
  subscription: "sub",
} as const;

/** A reserved prefix from {@link ID_PREFIXES}. */
export type IdPrefix = (typeof ID_PREFIXES)[keyof typeof ID_PREFIXES];

/**
 * orvacon's own payment identifier — the same value that rides the gateway as
 * `conversationId` / `merchant_oid`.
 *
 * Format: a prefixed ULID (`pay_01J…`, see {@link ID_PREFIXES}) — time-ordered
 * for index locality (sequential inserts keep B-tree pages warm, unlike random
 * UUIDv4), prefixed so an id is recognizable at a glance in logs and support
 * tooling. Generated by the core via {@link generatePaymentId}; applications
 * never mint payment ids.
 */
export type PaymentId = Brand<string, "PaymentId">;

const CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const PAYMENT_ID_PATTERN = /^pay_[0-9A-HJKMNP-TV-Z]{26}$/;

/**
 * Validate and brand a payment id (`pay_` + 26-char Crockford-base32 ULID).
 *
 * @throws TypeError if the value does not match the payment id format.
 */
export function paymentId(value: string): PaymentId {
  if (!PAYMENT_ID_PATTERN.test(value)) {
    throw new TypeError(`Payment id must match ${PAYMENT_ID_PATTERN}, got "${value}"`);
  }
  return value as PaymentId;
}

function encodeTime(ms: number): string {
  let rest = ms;
  const out = new Array<string>(10);
  for (let i = 9; i >= 0; i--) {
    out[i] = CROCKFORD.charAt(rest % 32);
    rest = Math.floor(rest / 32);
  }
  return out.join("");
}

function encodeRandom(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  let out = "";
  for (const b of bytes) {
    out += CROCKFORD.charAt(b & 31);
  }
  return out;
}

/**
 * Generate a fresh payment id: `pay_` + ULID (48-bit timestamp + 80 bits of
 * CSPRNG randomness, Crockford base32). `now` is injectable for tests.
 */
export function generatePaymentId(now: number = Date.now()): PaymentId {
  return paymentId(`${ID_PREFIXES.payment}_${encodeTime(now)}${encodeRandom()}`);
}

/**
 * Client-generated key that makes a mutating operation safe to retry.
 *
 * One key per *logical intent* (one payment attempt), generated by the caller
 * (e.g. `crypto.randomUUID()`) and reused unchanged on every retry of that same
 * intent — if the core generated it, a retry after a timeout would get a fresh
 * key and bypass deduplication entirely. The core enforces uniqueness atomically
 * in the database (unique constraint) with a bounded TTL; a replayed key returns
 * the original result, never a fresh charge.
 */
export type IdempotencyKey = Brand<string, "IdempotencyKey">;

/**
 * Validate and brand an idempotency key.
 *
 * @throws TypeError if the key is empty or longer than 255 characters.
 */
export function idempotencyKey(value: string): IdempotencyKey {
  if (value.length === 0 || value.length > 255) {
    throw new TypeError(`Idempotency key must be 1-255 characters, got length ${value.length}`);
  }
  return value as IdempotencyKey;
}

/**
 * A mutating request plus its client-generated {@link IdempotencyKey}. Every
 * money-moving call on the orvacon instance is idempotency-keyed; the core
 * consumes the key (dedup, replay) and the connector never sees it.
 */
export type Idempotent<I> = I & { idempotencyKey: IdempotencyKey };
