import type { Brand } from "./brand";
import type {
  AuthorizeInput,
  CaptureInput,
  ConnectorResult,
  Logger,
  NormalizedEvent,
  NormalizedEventType,
  OrvaconConnector,
  RawWebhook,
  RefundInput,
} from "./connector";
import type { Payment } from "./state";

/**
 * Client-generated key that makes a mutating operation safe to retry.
 *
 * One key per *logical intent* (one payment attempt), generated by the caller
 * (e.g. `crypto.randomUUID()`) and reused unchanged on every retry of that same
 * intent — if the core generated it, a retry after a timeout would get a fresh
 * key and bypass deduplication entirely. The core enforces uniqueness atomically
 * in the database (unique constraint) with a bounded TTL; a replayed key returns
 * the original result, never a fresh charge.
 */
export type IdempotencyKey = Brand<string, "IdempotencyKey">;

/**
 * Validate and brand an idempotency key.
 *
 * @throws TypeError if the key is empty or longer than 255 characters.
 */
export function idempotencyKey(value: string): IdempotencyKey {
  if (value.length === 0 || value.length > 255) {
    throw new TypeError(`Idempotency key must be 1-255 characters, got length ${value.length}`);
  }
  return value as IdempotencyKey;
}

/**
 * A mutating request plus its client-generated {@link IdempotencyKey}. Every
 * money-moving call on {@link Orvacon} is idempotency-keyed; the core consumes
 * the key (dedup, replay) and the connector never sees it.
 */
export type Idempotent<I> = I & { idempotencyKey: IdempotencyKey };

/**
 * The dev's database, bound through an adapter (bring-your-own-database). The
 * full adapter contract lives in the `@orvacon/adapter-*` packages; the core
 * only binds to this slot — it never imposes a datastore.
 */
export interface DatabaseAdapter {
  readonly id: string;
}

/** A behavior plugin, bound via `plugins: []`. Contract firmed up later. */
export interface OrvaconPlugin {
  readonly id: string;
}

/**
 * Handler invoked after the corresponding event's state change is persisted.
 * Receives the persisted {@link Payment} (final status — e.g. distinguishing
 * `partially_refunded` from `refunded`) and the triggering
 * {@link NormalizedEvent} (the moved delta and raw gateway payload).
 */
export type HookHandler = (payment: Payment, event: NormalizedEvent) => void | Promise<void>;

/**
 * Event-keyed lifecycle hooks, e.g. `{ "payment.captured": async (p) => … }`.
 * Handlers fire after the transition has been persisted; the `Payment` they
 * receive carries the final status (so a refund hook can distinguish
 * `partially_refunded` from `refunded`). Before/after-operation hooks widen
 * this surface together with the orchestration body.
 */
export type Hooks = Partial<Record<NormalizedEventType, HookHandler>>;

/** Retry/backoff policy for transient gateway failures. */
export type RetryConfig = {
  retries?: number;
  minTimeoutMs?: number;
  maxTimeoutMs?: number;
};

/**
 * Configuration for an orvacon instance. Validated fail-fast in {@link orvacon};
 * missing or invalid config throws at setup, not at the first payment.
 */
export type OrvaconConfig = {
  /** Bring-your-own-database adapter. Required — the core persists every payment, event, and ledger row. */
  database: DatabaseAdapter;
  /** Registered gateway connectors, e.g. `[iyzico({ ... })]`. */
  connectors: OrvaconConnector[];
  /** Behavior plugins. */
  plugins?: OrvaconPlugin[];
  /** Event-keyed lifecycle hooks. */
  hooks?: Hooks;
  /** Logger. Defaults to a no-op. */
  logger?: Logger;
  /** Catch-all for errors the core could not otherwise surface. */
  onError?: (error: Error) => void;
  /** Per-gateway-call timeout in milliseconds. */
  timeout?: number;
  /** Retry policy for transient gateway failures. */
  retry?: RetryConfig;
  /**
   * Ed25519 private key used to sign every webhook orvacon sends to the dev's
   * endpoint. Required — there is no unsigned-webhook mode. Generate a pair
   * with the CLI and load the private half from an environment variable; the
   * receiver verifies with the public half.
   */
  webhookSigningKey: string;
};

/**
 * The application-facing orchestrator. The app calls these without knowing which
 * gateway is behind a payment.
 */
export interface Orvacon {
  authorize(input: Idempotent<AuthorizeInput>): Promise<ConnectorResult>;
  capture(input: Idempotent<CaptureInput>): Promise<ConnectorResult>;
  refund(input: Idempotent<RefundInput>): Promise<ConnectorResult>;
  /**
   * Handle an inbound gateway webhook. `connectorId` comes from the callback
   * route (e.g. `/api/orva/callback/[connector]`).
   *
   * @remarks The return type will widen: beyond the {@link NormalizedEvent}, the
   * body also advances state, writes the ledger, enforces idempotency, and emits
   * the signed outgoing webhook. Kept narrow for the skeleton.
   */
  handleWebhook(connectorId: string, raw: RawWebhook): Promise<NormalizedEvent>;
}

/**
 * Construct an orvacon instance from a connector set and options.
 *
 * @remarks Skeleton — the orchestration body is not implemented yet.
 */
export function orvacon(_config: OrvaconConfig): Orvacon {
  throw new Error("orvacon(): not implemented");
}
