#!/usr/bin/env node

import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { supabaseSchema } from "@orvacon/adapter-supabase";
import { generateSigningKeyPair } from "@orvacon/cryptokit";

const VERSION = "0.0.1";

const HELP = `orvacon — provider-agnostic, TypeScript-first payment orchestration

Usage
  orvacon <command> [options]

Commands
  generate        print the database schema + default-deny RLS migration (--write to save it)
  keys            generate an Ed25519 webhook signing key pair

Options
  -v, --version   print the version
  -h, --help      show this help

Learn more: https://orvacon.com`;

const KEYS_GUIDANCE = `Generated an Ed25519 webhook signing key pair.

  ORVACON_WEBHOOK_SIGNING_KEY  secret — pass to orvacon({ webhookSigningKey }). Keep it in an env var; never commit it.
  ORVACON_WEBHOOK_PUBLIC_KEY   public — give to whoever verifies your webhooks. Safe to share.

The two ORVACON_* lines are written to stdout; redirect to capture them, e.g.  orvacon keys >> .env.local
`;

// Printed to stderr after the SQL goes to stdout — the deliberate "see → write →
// apply" recipe. The schema is printed (not auto-written) so the dev reads the
// RLS before applying it; this guidance walks them the rest of the way.
const GENERATE_GUIDANCE = `Generated orvacon's core schema + default-deny RLS (printed above).

  1. Review it — especially the RLS policies. This is your payment data's security
     boundary; read what you are about to apply.
  2. Save it:   orvacon generate --write   (-> supabase/migrations/<timestamp>_orvacon.sql)
  3. Apply it:  supabase db push

Keep your service_role key server-only — never expose it to the client or commit
it. service_role bypasses the RLS above by design, so that one key is the only
thing standing outside the boundary.
`;

const APPLY_GUIDANCE = `Review the migration — especially the RLS policies — then apply it:

  supabase db push

Keep your service_role key server-only; it bypasses the RLS above by design.
`;

/**
 * Assemble the migration. v1 emits the core schema only; once connectors and
 * kits can declare their own tables, their contributions would be merged in here.
 */
function migrationSql(): string {
  return `-- orvacon core schema + default-deny RLS.
-- Generated by \`orvacon generate\` (v${VERSION}). Review before applying.

${supabaseSchema()}
`;
}

/** Supabase migration prefix: a 14-digit UTC timestamp, YYYYMMDDHHMMSS. */
function utcStamp(): string {
  return new Date().toISOString().replace(/\D/g, "").slice(0, 14);
}

async function runGenerate(args: string[]): Promise<number> {
  const adapterAt = args.indexOf("--adapter");
  const adapter = adapterAt >= 0 ? args[adapterAt + 1] : "supabase";
  if (adapter !== "supabase") {
    process.stderr.write(`Unknown adapter: ${adapter}. v1 supports: supabase\n`);
    return 1;
  }

  const sql = migrationSql();

  // Default: print, so the dev reads the security policy before applying it.
  if (!args.includes("--write") && !args.includes("-w")) {
    process.stdout.write(sql);
    process.stderr.write(`\n${GENERATE_GUIDANCE}`);
    return 0;
  }

  const dir = join("supabase", "migrations");
  const force = args.includes("--force") || args.includes("-f");
  if (existsSync(dir)) {
    const existing = readdirSync(dir).filter((name) => name.endsWith("_orvacon.sql"));
    if (existing.length > 0 && !force) {
      process.stderr.write(
        `An orvacon migration already exists:\n  ${join(dir, existing[0])}\n\n` +
          "Refusing to overwrite — your edits (e.g. customized RLS) would be lost.\n" +
          "Delete it and re-run, or pass --force to write a new timestamped migration.\n",
      );
      return 1;
    }
  } else {
    mkdirSync(dir, { recursive: true });
  }

  const file = join(dir, `${utcStamp()}_orvacon.sql`);
  writeFileSync(file, sql);
  process.stderr.write(`Wrote ${file}\n\n${APPLY_GUIDANCE}`);
  return 0;
}

async function runKeys(): Promise<number> {
  const { publicKey, secretKey } = await generateSigningKeyPair();
  process.stdout.write(
    `ORVACON_WEBHOOK_SIGNING_KEY=${secretKey}\nORVACON_WEBHOOK_PUBLIC_KEY=${publicKey}\n`,
  );
  process.stderr.write(`\n${KEYS_GUIDANCE}`);
  return 0;
}

async function main(args: string[]): Promise<number> {
  const arg = args[0];

  if (arg === "-v" || arg === "--version") {
    process.stdout.write(`${VERSION}\n`);
    return 0;
  }

  if (arg === "generate") {
    return runGenerate(args.slice(1));
  }

  if (arg === "keys") {
    const sub = args[1];
    if (sub !== undefined && sub !== "generate") {
      process.stderr.write(`Unknown subcommand: keys ${sub}\nRun: orvacon keys\n`);
      return 1;
    }
    return runKeys();
  }

  if (!arg || arg === "-h" || arg === "--help") {
    process.stdout.write(`${HELP}\n`);
    return 0;
  }

  process.stderr.write(`Unknown command: ${arg}\nRun: orvacon --help\n`);
  return 1;
}

main(process.argv.slice(2))
  .then((code) => process.exit(code))
  .catch((error: unknown) => {
    process.stderr.write(`orvacon: ${error instanceof Error ? error.message : String(error)}\n`);
    process.exit(1);
  });
