/**
 * Generates the `src/__registry__` index the docs site reads at build time:
 *   - `index.ts`     — server-safe metadata plus each component's source (for the Code tab)
 *   - `previews.tsx` — lazy-loaded demo components (for the live Preview tab)
 *
 * The served, installable JSON is a separate artifact built by `orvacon registry
 * build` (see the `registry:serve` script). Both read the same `registry.json`.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface RegistryFile {
  path: string;
  type: string;
  target?: string;
}
interface RegistryItem {
  name: string;
  type: string;
  title?: string;
  description?: string;
  dependencies?: string[];
  registryDependencies?: string[];
  files?: RegistryFile[];
}
interface Registry {
  items: RegistryItem[];
}

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src", "__registry__");

const registry = JSON.parse(await readFile(join(root, "registry.json"), "utf8")) as Registry;

const entries = await Promise.all(
  registry.items.map(async (item) => {
    const main = item.files?.find((file) => file.path.endsWith(".tsx") || file.path.endsWith(".ts"));
    const source = main ? await readFile(join(root, main.path), "utf8") : "";
    return { item, source };
  }),
);

const indexTs = `// Generated by scripts/build-registry.ts — do not edit.

export interface RegistryEntry {
  name: string;
  title: string;
  description: string;
  dependencies: string[];
  registryDependencies: string[];
  source: string;
}

export const registryIndex: Record<string, RegistryEntry> = {
${entries
  .map(
    ({ item, source }) => `  ${JSON.stringify(item.name)}: {
    name: ${JSON.stringify(item.name)},
    title: ${JSON.stringify(item.title ?? "")},
    description: ${JSON.stringify(item.description ?? "")},
    dependencies: ${JSON.stringify(item.dependencies ?? [])},
    registryDependencies: ${JSON.stringify(item.registryDependencies ?? [])},
    source: ${JSON.stringify(source)},
  },`,
  )
  .join("\n")}
};
`;

const previews = registry.items.filter((item) => item.type === "registry:ui");
const previewsTsx = `// Generated by scripts/build-registry.ts — do not edit.
"use client";

import { type ComponentType, lazy } from "react";

export const previews: Record<string, ComponentType> = {
${previews
  .map((item) => `  ${JSON.stringify(item.name)}: lazy(() => import("@/registry/examples/${item.name}-demo")),`)
  .join("\n")}
};
`;

await mkdir(outDir, { recursive: true });
await writeFile(join(outDir, "index.ts"), indexTs);
await writeFile(join(outDir, "previews.tsx"), previewsTsx);

process.stderr.write(`Generated __registry__ for ${entries.length} item(s)\n`);
